### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by alexstrat** [getstation/theme#1]
- is `immutable` / `react-redux`/ `reselect` necessary dependencies?
- what is `linked-map.d.ts`?
- remove `Sample.tsx`?
- at least, list in Readme all exported functions/object and add a short description. At best, add the documentation as ts-doc.

**Comment by MathieuDebit** [comment]
- Removed `immutable` / `react-redux` / `reselect`
- Removed `linked-map.d.ts` and ignore `no-declaration-file` instead
- Removed `Sample.tsx`
- Working on Documentation 📝

**Comment by MathieuDebit** [comment]
Documentation done with `typedoc` 📝

**Comment by alexstrat** [comment]
🌮 🎉
