### ISSUE TITLE
Notification bullet

### ISSUE THREAD

**Issue by felipenmoura** [getstation/theme#11]
Hi.

I'm enjoying station so far, but I saw some "red bullets" in your screenshots at getstation.com, and here I don't get to see them!

The only way I know that there are notifications is in the last button at the bottom of the bar.
What should I do/enable to have a red dot in the services that have notifications?

Also, after reading the new content, those messages are still in the notification panel and the notifications button is still marked until I click in "mark all as read". Can't you synchronise it?
Franz, for example, shows the bullet in the service that has an unread notification, and as soon as you read it, it goes back to normal.

Personally, that is a critical behaviour as I use simultaneously 19 services.

Thanks.

**Comment by MathieuDebit** [comment]
Hi Felipe 👋

Thanks for your feedback! Notifications are disabled by default for all new services you install. When you receive your first notification in a service, Station displays a modal asking you to enable notifications or not. You can also manually toggle notifications via the sub-dock (when hovering an app, the bell icon next to the title). Once notifications are enabled, you should see red dots as expected.

Regarding the Notification Center, it should be synchronised with your notifications as you imagine. Furthermore, we are aware of usage issues and we plan to work on it, but our current efforts are toward other key features like the Quick-Switch.

Don't hesitate to report any issues in our community: https://community.getstation.com
This is where we gather all discussions and prioritise features and fixes.

Thanks!

**Comment by felipenmoura** [comment]
Hi.
Awesome, thanks.
I activated all the notifications and noticed that only three of the ones I use are not showing the red dot!
I'm currently using 16 different services, and only whatsapp and telegram are not showing the red bullet.
Also, gmail shows nothing even when I have a hangouts message (in the gtalk inside gmail).

Besides that, very nice work.

If I can add...I miss some mac features from chrome, like "double two-finger tap" to zoom in and out (also, pinching does not work for zooming either), and I also miss the "copy image" option.
